### ISSUE TITLE
Document x87 instruction provenance

### ISSUE THREAD

**Issue by clausecker** [Barebit/x86reference#12]
The current version of the reference does not document that the instructions `fsincos`, `fcos`, `fsin`, `fldenvd`, `fsaved`, `fprem1`, `frstord`, and `fstenvd` where only introduced with the 80387 processor.

**Comment by Kashio** [comment]
I think it should be noted that most if not all FP instructions are missing the `proc` attribute for when the instruction was first introduced.
It's also worth noting that with 80387 processor instruction, a new `proc` value should be added and not rely on the value `03: 80386` because according to [Wikipedia](https://en.wikipedia.org/wiki/X87#80387):

> Released in 1987, a full two years after the 386 chip

Unlike other FP instructions that were introduced with FPU that were released together with their counter-part like the 80287.

**Comment by BarebitOpenSource** [comment]
The missing `proc` attribute is because most of the FP instructions were introduced with 8087.

The `03` means 80387 in this case, the docs are not correct.

**Comment by BarebitOpenSource** [comment]
Moved to https://github.com/mazegen/x86reference/issues/16
