### ISSUE TITLE
Relicense suggestion

### ISSUE THREAD

**Issue by marler8997** [Barebit/x86reference#5]
May I suggest this be re licensed with a more open license?  MIT or BSD for example?

**Comment by BarebitOpenSource** [comment]
It was not easy to decide what license should I choose. I chose GPL because I spent quite a lot of time on this project and I'd like to see developers contribute back.

Do you have any specific use case where GPL is an issue although you are willing to contribute back?

**Comment by marler8997** [comment]
Your current license, the GPLv3 is quite restrictive.  I think there's 2 main reasons someone would decide to use a GPL license.  The first is they want to see developers contribute back to the project, and the second is they want to use their project as a means to "infect" as much code as they can with a GPL compatible license.

You seem to be in the first camp. This is the same thing Linus Torvalds wanted with Linux.  Going with his license would be much less restrictive than your current license (aka LGPLv2 https://github.com/torvalds/linux/blob/master/COPYING).  He's stated before how much he dislikes GPLv3 because of how restrictive it is and that he will never relicense linux to use it.  He's mostly mad that they decided to call it GPLv3 instead of giving it a new name which is confusing since it's very different from previous versions of the GPL.  This causes people to wonder why he doesn't "update" his license to the latest when his current license already satisfies his requirements, to get contributions back from the community.

Personally I care much more about people using my code than sharing their changes which is why I go with less restrictive licenses for my projects.  I believe that most people will share their changes anyway without me making it a requirement, but that's just my opinion.

**Comment by BarebitOpenSource** [comment]
Thank your for the long answer. I tried to get more information on the differences between v2 and v3, the tivoization, patents etc. but I realized I completely forgot about the Lesser GPL license that I should use for this project.

Now the question is whether it should be LGPLv2 or LGPLv3. I think the main thing Torvalds doesn't like about v3 is how the tivoization was resolved. I'm not sure if it is really important to avoid v3 for this project because if I choose v2, I'll be kind of stuck with it - when (if) v4 will be available, I would need to rethink all the issues again before moving to v4 (I assume v4 would not disclaim v3).

Do you think it is important to choose LGPLv2 for this project instead of v3?

**Comment by marler8997** [comment]
I'm probably not the best person to ask about the subtle differences between each GPL license :) However, from the little I looked into it, the "lesser" versions of the licenses are much less restrictive.  I think you would be fine going with either LGPLv2 or LGPLv3.  For me personally, I would be much more comfortable using this project if it were licensed with one of those.

**Comment by BarebitOpenSource** [comment]
It is licensed with LGPLv3 now. Thank you for the suggestion.
